In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [2]:
import pandas as pd

In [3]:
data= pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [4]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data.shape

(10000, 14)

In [6]:
data.drop(columns= ['RowNumber','Surname'],axis=1,inplace=True)

Data cleaning

In [7]:
data.head()

,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
data.isnull().sum()

CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   CreditScore      10000 non-null  int64
 2   Geography        10000 non-null  object
 3   Gender           10000 non-null  object
 4   Age              10000 non-null  int64
 5   Tenure           10000 non-null  int64
 6   Balance          10000 non-null  float64
 7   NumOfProducts    10000 non-null  int64
 8   HasCrCard        10000 non-null  int64
 9   IsActiveMember   10000 non-null  int64
 10  EstimatedSalary  10000 non-null  float64
 11  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(2)
memory usage: 937.6+ KB

In [ ]:
data.describe()

give description of numerical column 
hume include all nhi karna hai
data.describe(include='all') <- agar hum ye likhte hai to vo not a number values ko bhi describe karega

In [ ]:
data.info('Age')

In [ ]:
data['Exited'].value_counts()

to know data particular column have binary classification or multiple classification

In [ ]:
data['Gender'].value_counts()

In [ ]:
data['Gender']=data['Gender'].map({'Male':1,'Female':0})

In [ ]:
data.head(10)

In [ ]:
data['Geography'].value_counts()

In [ ]:
data = pd.get_dummies(data,columns=['Geography'],drop_first=True,dtype=int)

ONE HOT ENCODING

In [ ]:
data.head(10)

In [ ]:
x= data.drop(columns=['Exited'])

In [ ]:
y=data['Exited']

In [ ]:
x

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train.shape

In [ ]:
x_test.shape

In [ ]:
from sklearn.preprocessing import StandardScaler

Scaling

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train=scaler.fit_transform(x_train)

In [ ]:
x_train

In [ ]:
x_test=scaler.transform(x_test)

In [ ]:
x_test

In [ ]:
import tensorflow
from tensorflow import keras 
from tensorflow.keras.layers import Dense  # dense use for adding the layer 
from tensorflow.keras.models import Sequential #Sequential is like a model

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(3,activation = 'sigmoid',input_dim=12))
model.add(Dense(2,activation = 'sigmoid'))
model.add(Dense(1,activation = 'sigmoid'))

In [ ]:
model.summary()

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [ ]:
history= model.fit(x_train,y_train,epochs=50)   # it divide data into 250badges 8000/250 = 1badge

In [ ]:
y_predict=model.predict(x_test)

In [ ]:
y_predict

In [ ]:
y_prob=np.where(y_predict>0.5,1,0)

In [ ]:
y_prob

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print('ANN result is =',accuracy_score(y_test,y_prob)*100)